// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands, plugins, or emoji config.

import type Bot from './bot';

// prettier-ignore
declare module '@seedcord/gateway' {
    interface Core {
        storage: (typeof Bot)['storage'];
    }
    interface SlashRegistry {
        get_storage: { options: { key: { kind: 'string'; required: true } }; cache: 'cached' };
        ping: { options: { detailed: { kind: 'boolean'; required: false } }; cache: 'cached' };
        write_storage: { options: { key: { kind: 'string'; required: true }; value: { kind: 'string'; required: true } }; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
