// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashRegistry {
        ping: { options: { detailed: { kind: 'boolean'; required: false } }; cache: 'cached' };
        write_storage: { options: {}; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
